In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [4]:
original_data = pd.read_csv('titanic.csv')
df = original_data.copy()

In [5]:
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.shape

(891, 13)

In [7]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   PassengerId  891 non-null    int64
 2   Survived     891 non-null    int64
 3   Pclass       891 non-null    int64
 4   Name         891 non-null    str
 5   Sex          891 non-null    str
 6   Age          714 non-null    float64
 7   SibSp        891 non-null    int64
 8   Parch        891 non-null    int64
 9   Ticket       891 non-null    str
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    str
 12  Embarked     889 non-null    str
dtypes: float64(2), int64(6), str(5)
memory usage: 90.6 KB

In [9]:
df.drop(columns = ['Unnamed: 0','PassengerId','Name'],inplace = True)

In [11]:
df['GroupSize'] = 1 + df['Parch'] + df['SibSp']

In [12]:
df.describe()

,Survived,Pclass,Age,SibSp,Parch,Fare,GroupSize
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,1.904602
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,1.613459
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,1.000000
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,1.000000
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,2.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,11.000000

In [13]:
label_encoder = LabelEncoder()
df['Embarked'] = label_encoder.fit_transform(df['Embarked'])

In [14]:
df['Sex'] = label_encoder.fit_transform(df['Sex'])

In [ ]:
df['Survived'].value_counts(normalize=True)

In [ ]:
df['Pclass'].value_counts(normalize = True)

In [ ]:
df['Sex'].value_counts(normalize = True)

In [ ]:
df['Ticket'].value_counts().head(10)

In [ ]:
df['Cabin'].value_counts().head(10)

In [ ]:
df['Embarked'].value_counts(normalize = True)

In [ ]:
sns.histplot(data = df, x = 'Age',kde = True)
plt.title('Distribution of Age')
plt.show()

In [ ]:
sns.histplot(data = df, x = 'Fare',kde = True)
plt.title('Distribution of Fare')
plt.show()

In [ ]:
sns.countplot(data = df, x = 'Survived')
plt.title('Count of Survival')
plt.show()

In [ ]:
sns.countplot(data = df, x = 'Pclass')
plt.title('Count of Pclass')
plt.show()

In [ ]:
sns.countplot(data = df, x = 'Sex')
plt.title('Count of Sex')
plt.show()

In [ ]:
sns.countplot(data = df, x = 'Embarked')
plt.title('Count of Embarked')
plt.show()

In [ ]:
sns.countplot(data = df, x = 'SibSp')
plt.title('Count of Siblings and Spouse')
plt.show()

In [ ]:
sns.countplot(data = df, x = 'Parch')
plt.title('Count of Parenrt/Children')
plt.show()

In [ ]:
df.groupby('Survived').mean(numeric_only=True)

In [ ]:
pclass_survival = df.groupby('Pclass')['Survived'].mean()
pclass_survival = pclass_survival.to_frame().reset_index()
pclass_survival.plot(kind = 'bar',x = 'Pclass',y = 'Survived',color = 'blue')
plt.ylabel('Survival Rate')
plt.xticks(rotation = 0)

In [ ]:
embarked_survival = df.groupby('Embarked')['Survived'].mean()
embarked_survival = embarked_survival.to_frame().reset_index()
embarked_survival.plot(kind = 'bar',x ='Embarked',y = 'Survived',color = 'red')
plt.ylabel('Survival Rate')
plt.xticks(rotation = 0)
plt.show()

In [ ]:
sex_survival = df.groupby('Sex')['Survived'].mean()
sex_survival = sex_survival.to_frame().reset_index()
sex_survival.plot(kind = 'bar', x = 'Sex',y = 'Survived',color = 'green')
plt.ylabel('Survival Rate')
plt.xticks(rotation = 0)
plt.show()

In [ ]:
sns.boxplot(data=df, x='Survived', y='Fare', hue='Survived', legend=False)

In [ ]:
sns.scatterplot(
    data=df, 
    x='Age', 
    y='Fare', 
    hue='Survived',  
    palette='Set1', 
    alpha=0.7, 
    s=80
)

In [ ]:
sns.catplot(
    data=df,
    x='Embarked',
    hue='Survived',
    col='Pclass',
    kind='count',
    palette='Set1',
    height=5,
    aspect=0.8
)

In [ ]:
sns.barplot(data = df, x= 'GroupSize',y = 'Survived',errorbar=None)

In [ ]:
df['Survived'] - df['Survived'].astype(int)
df['Sex'] = df['Sex'].map({'male':1,'female':0})
numerical_columns = df.select_dtypes(include=[np.number])
numerical_columns

In [ ]:
sns.heatmap(
    numerical_columns.corr(), 
    annot=True, 
    cmap='coolwarm', 
    fmt=".2f", 
    vmin=-1, 
    vmax=1,
    linewidths=0.5
)